### PR TITLE
Add condition and JSON import file for compatibility with ACF5 Pro.

### PR DESCRIPTION
**Pull request by mikespainhower**

### CODE REVIEW

**Comment by kalenjohnson** [comment]
Wow I can't believe this is almost a year old, feel pretty bad about that. Thanks for contributing!

**Comment by retlehs** [comment]
geez @kalenjohnson. nice one @mikespainhower :tada:

**Comment by kalenjohnson** [comment]
I ALREADY SAID I FEEL BAD @retlehs

**Comment by mikespainhower** [comment]
haha, no worries! thanks :)

**Pull request merged**
